# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7c7d283c86db6f846b76ec1ed7cea4e718743d637f0b6b178bec48654004db58711cfb80e0fdde2eec9681ddeb71821fa41b3bbb68fafb0097eaa0c8e2b8af5

test:
  secret_key_base: 90aad49d9e6b2bff8b711bf52fa42e167f3d8deaa5e9fe2064f183ae67f7e3c1dfb1e8686e16a17b11f3dddc27c58f5e5bb3d0b7a992df5fc2fa7e51e4a112a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
